--Executar para poder cadastrar e logar no sistema

CREATE DATABASE U3;

CREATE TABLE USUARIO(CPF VARCHAR(12) PRIMARY KEY NOT NULL, RG VARCHAR(10) NOT NULL, EMAIL VARCHAR(50) NOT NULL, DATA_NASCIMENTO DATE NOT NULL, SENHA VARCHAR(255) NOT NULL, NOME VARCHAR(50) NOT NULL);